version: "3.9"
services:
  nginx:
    build: nginx
    ports: 
      - "80:80"
      - "443:443"
  frontend:
    build: frontend
    ports:
      - "3000:3000" 
  backend: 
    build: backend
    ports:
      - "5000:5000"
  db:
    image: mysql
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: 'market'
      MYSQL_ROOT_PASSWORD: 'Distant_7'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3360:3306'
  